# Generated by Django 3.0.8 on 2020-07-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produtos',
            table='produtos',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
